version: '3.8'

services:
  bot:
    build: .
    container_name: casting_bot_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./casting_userbot.session:/app/casting_userbot.session
      - ./casting_bot.db:/app/casting_bot.db
    restart: always
    networks:
      - default

  admin:
    build: .
    container_name: casting_admin_app
    command: ["uvicorn", "admin.main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env
    volumes:
      - ./casting_bot.db:/app/casting_bot.db
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8002:8000"
    restart: always
    networks:
      - default

networks:
  default:
